### ISSUE TITLE
openBySpreadsheetId throwing error

### ISSUE THREAD

**Issue by shyjal** [tanaikech/DocsServiceApp#2]
DocsServiceApp.openBySpreadsheetId(spreadsheetId)
    .getSheetByName(sheetName)
    .getImages()

is not working as expected inside a macro.

Following error is thrown while executing 

`Exception: We're sorry, a server error occurred. Please wait a bit and try again.
SpreadsheetAppp	@ SpreadsheetAppp.gs:11
openBySpreadsheetId	@ main.gs:15`

**Comment by tanaikech** [comment]
Thank you for your comment. I apologize for the inconvenience. Unfortunately, I cannot replicate your issue. When I tested the script, no error occurs. The images in a sheet can be retrieved. I deeply apologize for this. So in order to correctly understand about your current situation, can you provide the detail flow for replicating your issue? By this, I would like to confirm it.

By the way, when a lot of images are existing in the sheet, an error might occur. I'm worry about this situation. How about this?

And, as other method for retrieving the images from cells, I think that for example, the pattern 1 of [this my answer](https://stackoverflow.com/a/64040243) can be used. How about this?

**Comment by shyjal** [comment]
It's strange, I always get the error even tho I added the library and drive service.

By the way, are you using the solution mentioned in pattern 1 internally inside this library? by exporting xlsx file?

**Comment by shyjal** [comment]
If the performance of both patterns is the same, I would go with pattern 1. Please confirm if the process is the same in both patterns.

**Comment by tanaikech** [comment]
About your request of `If the performance of both patterns is the same, I would go with pattern 1. Please confirm if the process is the same in both patterns.`, I have explained about the pattern 1 and the pattern 2 in [my answer](https://stackoverflow.com/a/64040243). Could you please confirm it? If you cannot understand my English, I apologize.
